### ISSUE TITLE
能否识别 zen7.dll 这种文件名

### ISSUE THREAD

**Issue by ivysrono** [breakwa11/gtp4zen#3]
现在只能识别 zen.dll 导致要把引擎复制在两个文件夹，还容易搞混。
如果能像 leelazero 识别权重一样来识别 dll，那就方便很多了。
毕竟针对 zen，所以只要能识别出 zen6.dll 和 zen7.dll 就足够了。

**Comment by breakwa11** [comment]
由于zen.dll不能改名，现在用放两个子文件夹的方式实现

**Comment by ivysrono** [comment]
源码貌似是没啥问题了，但是说明中还有 zen7.dll 和 zen6.dll 的描述。
还有 release 中的 0.3.5 应该不是用最新源码编译的吧，gtpshell输出还是 v 0.3.3

**Comment by breakwa11** [comment]
已更换，重新下载吧
