### ISSUE TITLE
能否加入首位计算量参数

### ISSUE THREAD

**Issue by ivysrono** [breakwa11/gtp4zen#5]
如果没有理解错，现在的 -s 参数限定的应该是总计算量。
不知能否实现首位计算量限定，如：
```
-S10000 表示每一步当首位计算量超过10000时停止。
-S5000+ 表示每一步当首位计算量超过次位计算量5000时停止。
-S10000,5000+ 满足其中一个条件时停止。
```

**Comment by breakwa11** [comment]
我不太明白你的意思，能不能举个例子

**Comment by ivysrono** [comment]
![图片](https://user-images.githubusercontent.com/2649544/54861111-e5d95180-4d5e-11e9-92c2-caff11bf36c5.png)
这是奋奋狮子做的ZenGTP的输出，Q17就是首位，Q16就是次位，箭头后的数字就是其计算量。
按照我的观察，gtp4zen控制的是所有选点的总计算量，-s 25000 大致相当于首位 10000，但没有严格测试。
